apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
    <head><title> Devops</title></head>
      <body><h1>Hello DevOps! HEllO DEVOPS!</h1></body>
    </html>

