name: CI/CD Pipeline - Deploy Nginx on Kubernetes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Print message
      run: echo "Runner is working!"

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > kubeconfig
        mkdir -p $HOME/.kube
        mv kubeconfig $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Install Helm
      run: |
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy to Kubernetes using Helm
      run: |
        helm upgrade --install nginx-hello /deployment/my-nginx \
          --set service.type=NodePort \
          --set image.repository=nginx 
